services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

    environment:
    # easiest fix for fresh docker without https. temporary purposes.
      - N8N_SECURE_COOKIE=false
    # webhook env variables  
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - TZ=Asia/Manila
      - WEBHOOK_URL=http://YOUR_PUBLIC_IP:5678/
     # ollama connection
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  n8n_data: